permit:
  - BSD.*
  - MIT.*
  - Apache.*
  - MPL.*
  - ISC
  - WTFPL
  - Unlicense

ignore-packages:
  # crypto/internal/boring is released under the openSSL license as a part of the Golang Standard Library
  - crypto/internal/boring

