release:
  prerelease: true

builds:
  - binary: dive
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

dockers:
  -
    binary: dive
    image_templates:
    - "wagoodman/dive:{{ .Tag }}"
    - "wagoodman/dive:v{{ .Major }}"
    - "wagoodman/dive:v{{ .Major }}.{{ .Minor }}"
    - "wagoodman/dive:latest"
    - "quay.io/wagoodman/dive:{{ .Tag }}"
    - "quay.io/wagoodman/dive:v{{ .Major }}"
    - "quay.io/wagoodman/dive:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/wagoodman/dive:latest"

archive:
  format: tar.gz

  format_overrides:
    - goos: windows
      format: zip

nfpm:
  license: MIT
  maintainer: Alex Goodman
  homepage: https://github.com/wagoodman/dive/
  formats:
    - deb
    - rpm

brew:
  github:
    owner: wagoodman
    name: homebrew-dive
