FROM alpine:3.10
ARG DOCKER_CLI_VERSION="19.03.1"
RUN apk --update add curl &&\
    curl -L https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_CLI_VERSION.tgz | \
    tar -xzf - docker/docker --strip-component=1 -C /tmp
COPY dist/dive_linux_amd64/dive /
ENTRYPOINT ["/dive"]
